# hier werden allgemeine Pfade des Programms definiert
[ParserConfig]
XProzessPath		=	"../xml.files/Anzeige zur Beschäftigung einer schwangeren oder stillenden Frau bearbeiten.xml"
XDatenfeldPath		=	"../xml.files/S00000094V1.0_xdf2.xml"
OntologyPath 		=	"/home/raupach/Projects/gerps-onto/ontology-population/ontology/gerPS-Onto.rdf"
outputPath			=	"/home/raupach/Projects/gerps-onto/ontology-population/gerPS-Onto-populated.ttl"
#nothing for rdf/xml
RDFLanguage			= 	"ttl"
#Codelists for XDatenfeld
codelisten			= 	["../xml.files/C00000020_genericode.xml","../xml.files/C00000021_genericode.xml","../xml.files/C60000006_genericode.xml","../xml.files/C60000020_genericode.xml"]


# Klassen und Properties für XProzess Datei
[XProzess]
baseURL = "https://w3id.org/GerPS-onto/ontology#"
dataFieldIndividual = "https://w3id.org/GerPS-onto/ontology#"
process = "https://w3id.org/GerPS-onto/ontology#GERPSE010"
sub_process = "https://w3id.org/GerPS-onto/ontology#GERPSE011"
service = "https://w3id.org/GerPS-onto/ontology#GERPSE008"
agent = "https://w3id.org/GerPS-onto/ontology#GERPSE001"
Hauptakteur = "https://w3id.org/GerPS-onto/ontology#GERPSE007"
Mitwirkende = "https://w3id.org/GerPS-onto/ontology#GERPSE009"
Ergebnissempfaenger = "https://w3id.org/GerPS-onto/ontology#GERPSE005"
rag = "https://w3id.org/GerPS-onto/ontology#GERPSE012"
data_fields = "https://w3id.org/GerPS-onto/ontology#GERPSE017"
basis = "https://w3id.org/GerPS-onto/ontology#GERPSE006"
has_process = "https://w3id.org/GerPS-onto/ontology#GERPSP005"
has_sub_process = "https://w3id.org/GerPS-onto/ontology#GERPSP006"
is_running = "https://w3id.org/GerPS-onto/ontology#GERPSP004"
based_on = "https://w3id.org/GerPS-onto/ontology#GERPSP001"
participates = "https://w3id.org/GerPS-onto/ontology#GERPSP002"
has_resource = "https://w3id.org/GerPS-onto/ontology#GERPSP008"
has_type = "https://w3id.org/GerPS-onto/ontology#GERPSP009"
tauscht_aus_mit = "https://w3id.org/GerPS-onto/ontology#tauscht_aus_mit"
trades_with = "https://w3id.org/GerPS-onto/ontology#tauscht_aus_mit"
data_field_id = "https://w3id.org/GerPS-onto/ontology#GERPSP012"
leika_id = "https://w3id.org/GerPS-onto/ontology#GERPSP016"
id = "http://BPMNbasedOntology#id"
name = "http://BPMNbasedOntology#name"
provoAgent = "http://www.w3.org/ns/prov#agent"
provoRole = "http://www.w3.org/ns/prov#Role"
provoAssociation = "http://www.w3.org/ns/prov#Association"
provoQA = "http://www.w3.org/ns/prov#qualifiedAssociation"
provoHadRole = "http://www.w3.org/ns/prov#hadRole" 
has_process_participants="https://w3id.org/GerPS-onto/ontology#GERPSP017"

# Klassen und Properties für das Parsen von zugehöriger XDatenfeldDatei
[XDatenfeld]
baseURLFields = "https://test.schema-repository.fitko.dev/fields/baukasten/"
baseURLRules = "https://test.schema-repository.fitko.dev/rules/baukasten/"
baseURLGroups = "https://test.schema-repository.fitko.dev/groups/baukasten/"
baseURLSchema = "https://test.schema-repository.fitko.dev/schema/baukasten/"
baseURL = "https://w3id.org/GerPS-onto/FIMDatenfelder#"
Stammschemata = "https://w3id.org/GerPS-onto/FIMDatenfelder#J000002"
Struktur = "https://w3id.org/GerPS-onto/FIMDatenfelder#J000003"
Datenfeld = "https://w3id.org/GerPS-onto/FIMDatenfelder#J000004"
Datenfeldgruppe = "https://w3id.org/GerPS-onto/FIMDatenfelder#J000005"
Regel = "https://w3id.org/GerPS-onto/FIMDatenfelder#J000001" 
StrukturHead="https://w3id.org/GerPS-onto/FIMDatenfelder#J000028"
hat_Regel = "https://w3id.org/GerPS-onto/FIMDatenfelder#JP000005"
hat_enthaelt = "https://w3id.org/GerPS-onto/FIMDatenfelder#JP000001"
name = "http://BPMNbasedOntology#name"
id = "https://w3id.org/GerPS-onto/ontology#hat_datenfeldID"
Identification="https://w3id.org/GerPS-onto/FIMDatenfelder#J000028"
hasIdentificaton="https://w3id.org/GerPS-onto/FIMDatenfelder#JP000009"
hasDescription="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000001"
hasHelpTextInput="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000002"
hasHelpTextOutput="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000003"
hasFieldtype="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000004"
hasDatatype="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000005"
hasClarification="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000006"
hasContent="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000007"
hasPrefilling="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000008"
hasCodelistReference="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000009"
hasMediaType="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000010"
hasMaxSize="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000011"
hasVersion="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000012"
hasAuthor="https://w3id.org/GerPS-onto/FIMDatenfelder#JD000014"
basis="https://w3id.org/GerPS-onto/ontology#Handlungsgrundlage"
based_on="https://w3id.org/GerPS-onto/ontology#basiert_auf"
connectVersion="https://w3id.org/GerPS-onto/FIMDatenfelder#JP000009"

# Klassen für strukturelles Parsen von XProzess
[BPMN]
baseURL = "https://w3id.org/GerPS-onto/ontology#"
SubProcess = "http://BPMNbasedOntology#SubProcess"
task = "http://BPMNbasedOntology#Task"
Callactivity = "http://BPMNbasedOntology#CallActivity"
ExclusiveGateway = "http://BPMNbasedOntology#ExclusiveGateway"
InclusiveGateway = "http://BPMNbasedOntology#InclusiveGateway"
ParallelGateway = "http://BPMNbasedOntology#ParallelGateway"
SequenceFlow = "http://BPMNbasedOntology#SequenceFlow"
id = "http://BPMNbasedOntology#id"
name = "http://BPMNbasedOntology#name"
attachedTo = "http://BPMNbasedOntology#is_attachedToRef"
sourceRef = "http://BPMNbasedOntology#has_sourceRef"
targetRef = "http://BPMNbasedOntology#has_targetRef"

# Hier wird das Mapping definiert
[Mapping]

# Hier werden die Klassen im Key-Value-Prinzip durch die sameAs Property Verknüpft
[Mapping.sameAs]
[[Mapping.sameAs.entry]]
key     =   "https://w3id.org/GerPS-onto/ontology#Hauptakteur"
value   =   "https://semiceu.github.io/CPOV/releases/2.00/#Public%20Organisation"
[[Mapping.sameAs.entry]]
key     =   "https://w3id.org/GerPS-onto/ontology#Ergebnissempfänger"
value   =   "https://semiceu.github.io/Core-Business-Vocabulary/releases/2.00/#Legal%20Entity"
[[Mapping.sameAs.entry]]
key     =   "https://w3id.org/GerPS-onto/ontology#Leistung"
value   =   "https://semiceu.github.io/CPSV-AP/releases/3.1.0/#Public%20Service"
[[Mapping.sameAs.entry]]
key     =   "https://w3id.org/GerPS-onto/ontology#Handlungsgrundlage"
value   =   "http://publications.europa.eu/resource/cellar/917d16b5-28f6-11e8-b5fe-01aa75ed71a1.0001.01/DOC_1#LegalResource"

# Hier werden die Klassen im Key-Value-Prinzip durch die subClassOf-Property Verknüpft
[Mapping.subClassOf]
[[Mapping.subClassOf.entry]]
key     =    "http://BPMNbasedOntology#Agent"
value   =    "https://semiceu.github.io/Core-Person-Vocabulary/releases/2.00/#Agent"
[[Mapping.subClassOf.entry]]
key     =   "https://w3id.org/GerPS-onto/ontology#Mitwirkende"
value   =   "https://semiceu.github.io/Core-Business-Vocabulary/releases/2.00/#Formal%20Organization"
[[Mapping.subClassOf.entry]]
key     =   "https://w3id.org/GerPS-onto/ontology#Datenfelder"
value   =   "https://semiceu.github.io/CPSV-AP/releases/3.1.0/#Evidence"
[[Mapping.subClassOf.entry]]
key     =   "https://w3id.org/GerPS-onto/ontology#Dokument"
value   =   "https://semiceu.github.io/CPSV-AP/releases/3.1.0/#Evidence"
[[Mapping.subClassOf.entry]]
key     =   "https://w3id.org/GerPS-onto/ontology#Prozess"
value   =   "https://semiceu.github.io/CPSV-AP/releases/3.0.0/#Rule"

# Hier werden die Klassen im Key-Value-Prinzip durch die subClassOf-Property Verknüpft (umgekehrt) verknüft
[Mapping.superClassOf]
